#!/usr/bin/env bash
# A script to install nginx server and define a simple page response for port 80
sudo apt-get -y install nginx

sudo echo "Hello World!" >> /var/www/index.html
sudo tee /etc/nginx/conf.d/hello.conf > /dev/null <<EOF
server {
	listen 80;
	location / {
		root /var/www/html;
		index index.html;
	}
}
EOF

sudo nginx -s reload
