#!/usr/bin/env bash
# A script to install nginx server and define a simple page response for a port
apt-get update
apt-get -y install nginx
echo "Hello World!" > tee /var/www/html/index.html
nginx -s reload
