#!/usr/bin/env bash
# A script to install nginx server and define a simple page response for port 80
apt-get update
apt-get install -y curl wget git
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
tee /etc/nginx/conf.d/hello.conf > /dev/null <<EOF
server {
        listen 80;
	server_name 52.91.134.249;
        location / {
                root /var/www/html;
                index index.html;
        }
}
EOF
sudo service nginx start
sudo nginx -s reload
