#!/usr/bin/env bash
# A Bash script containing commands to automatically configure a redirect_me
apt-get update
apt-get install -y curl wget git
apt-get install nginx
sudo service nginx start
replace="location \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}\n\tlocation \/ {"
sudo sed -i "s/location \/ {/$replace/" /etc/nginx/conf.d/hello.conf
sudo nginx -s reload
