#!/usr/bin/env bash
# A Bash script containing commands to automatically configure a redirect_me
apt-get update
apt-get install -y curl wget git
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
if [ ! -f "/etc/nginx/conf.d/hello.conf" ]
then
        tee /etc/nginx/conf.d/hello.conf > /dev/null <<EOF
server {
        listen 80;
        server_name lq-enterprise.tech;
        root /var/www/html;
        index index.html;
        location / {
        }
}
EOF
fi
replace="location \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}\n\tlocation \/ {"
sed -i "s/location \/ {/$replace/" /etc/nginx/conf.d/hello.conf
service nginx start
nginx -s reload
