#!/usr/bin/env bash
# A Bash script containing commands to automatically configure a redirect_me
default="/etc/nginx/sites-available/default"
apt-get update
apt-get install -y curl wget git
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
if [ -f "$default" ]
then
        rm "$default"
fi

tee "$default" > /dev/null <<EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name "lq-enterprise.tech";
        root /var/www/html;
        index index.html;
        location / {
        }
}
EOF
replace="location \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}\n\tlocation \/ {"
sed -i "s/location \/ {/$replace/" "$default"
if [ ! -f "$default" ]
then
        ln -s "$default" "/etc/nginx/sites-enabled/"
fi
echo "Ceci n'est pas une page" | tee /var/www/html/not_found.html > /dev/null
sed -i '/index index.html not_found.html/!{ s/index index.html/index index.html not_found.html/; }' "$default"
new_string="location / {\n\t\terror_page 404 /not_found.html;"
replace="location / {"
sed -i "s|$replace|$new_string|" "$default"
header="location / {\n\t\tadd_header X-Served-By \"\$hostname\";\n"
sed -i "s|$replace|$header|" "$default"
service nginx start
nginx -s reload
