#!/usr/bin/env bash
# Display information about subdomains
num_args="$#"
if [ "$num_args" -ge 1  ]
then
	domain="$1"
	if [ "$num_args" -ge 2 ]
	then
		sub=$2
		result="$(dig "$2.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)"
		echo "$result" | awk -F" " -v subdom="$sub" '{print "The subdomain ", subdom, " is a ", $4, " record and points to ", $5}'
	else
		result_www="$(dig www."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)"
		echo "$result_www" | awk -F" " '{print "The subdomain www is a ", $4, " record and points to ", $5}'

		result_lb_01="$(dig lb-01."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)"
		echo "$result_lb_01" | awk -F" " '{print "The subdomain lb-01 is a ", $4, " record and points to ", $5}'

		result_web_01="$(dig web-01."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)"
		echo "$result_web_01" | awk -F" " '{print "The subdomain web-01 is a ", $4, " record and points to ", $5}'
		
		result_web_02="$(dig web-02."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)"
		echo "$result_web_02" | awk -F" " '{print "The subdomain web_02 is a ", $4, " record and points to ", $5}'
	fi
fi
