#!/usr/bin/env bash
#A Bash script that manages 'manage_my_process'
sudo su -
case "$1" in
	"start")
		"$("./manage_my_process" &)"
		touch "/var/run/my_process.pid"
		chmod 666 "/var/run/myscript.pid"
		cat "$(pgrep -f "./manage_my_process")" >> "/var/run/my_process.pid"
		echo "manage_my_process started"
		;;
	"stop")
		kill "$(pgrep -f "./manage_my_process")"
		rm "/var/run/my_process.id"
		echo "manage_my_process stopped"
		;;
	"restart")
		kill "$(pgrep -f "./manage_my_process")"
		rm "/var/run/my_process.pid"
		touch "/var/run/my_process.pid"
		chmod 666 "/var/run/my_process.pid"
		cat "$(pgrep -f "./manage_my_process")" >> "/var/run/my_process.pid"
		"$("./manage_my_process" &)"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
