#!/usr/bin/env bash
#A Bash script that displays 'To infinity and beyond' indefinitely
function sigterm_handler {
	echo "I am invincible!!!"
}
trap 'sigterm_handler' SIGTERM
i=1
while [ $i -ge 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
