#!/usr/bin/env bash
#A Bash script that indefinitely writes to a file and pauses for 2 secs in betweeen each write
file="/tmp/my_process"
i=1
while [ $i -ge 1 ]
do
	if [ -e "$file" ]
	then
		echo "I am alive!" >> "$file"
	else
		touch "/tmp/my_process"
		echo "I am alive!" >> "$file"
	fi
	sleep 2
done
