#!/usr/bin/env bash
#A Bash script that displays the visitor IP along with the HTTP status code\
 from the Apache log file
awk -F '[ ]+' '{ print $1, $5 }' apache-access.log | awk -F '[- ]+' '{ print $1, $2 }' | awk -F '[]]+' '{ print $1, $2 }'
