#!/usr/bin/env bash
#A Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
awk -F '[ -]+' '{
	for (i= 2; i <= NF; i++) {
		if ($i + 0 == $i) {
			num = i + 0
			print $1, $num
			break;
		}
	}
}' apache-access.log
