#!/usr/bin/env bash
#A Bash script that displays the visitor IP along with the HTTP status code\
 from the Apache log file]
awk '{ if ($9 != "\"-\"") { print $1, $9 } else { print $1, $7 } }' apache-access.log
